[package]
name = "rsubst"
version = "0.1.0"
edition = "2024"

[profile.release]
lto = "fat"
codegen-units = 1
opt-level = "z"
#strip = true
panic = "abort"

[dependencies]
anyhow = "1"
minijinja = "2"
